# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18pVHzmMjf5vBQh8x5xCu0cVHHeEGPo6w
"""


import streamlit as st
import pickle

load_model=pickle.load(open('model.sav','rb'))

loder_vec=pickle.load(open('vectorizer.pkl','rb'))

def spam_detect(message):

  input_data = [message]
  input_count = loder_vec.transform(input_data)
  prediction = load_model.predict(input_count)

  if prediction[0] == 1:
    return 'Spam'
  else:
    return 'Not Spam'


def main():
    st.title('Spam Detection')
    message = st.text_input('Enter a message')
    if st.button('Predict'):
        result =spam_detect(message)
        st.success(result)

if __name__ == '__main__':
  main()